# fly.toml file generated for cardstock-log-shipper on 2021-09-08T17:13:01-05:00

app = "cardstock-log-shipper"

kill_signal = "SIGINT"
kill_timeout = 5

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[metrics]
  path = "/metrics"
  port = 9598

[[services]]
  http_checks = []
  internal_port = 8686
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.tcp_checks]]
    grace_period = "3s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
